sudo: false
language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
before_install:
  - travis_retry gem update --system || travis_retry gem update --system 2.7.8
  - travis_retry gem install bundler --no-document || travis_retry gem install bundler --no-document -v 1.17.3
cache: bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - RUBYOPT=$RSPEC_RUBYOPT bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
branches:
  only:
    - master
notifications:
  slack:
    secure: jYJBCIqtreEfU6aleufyqnI6xWDfJjFXJEOXqVq0xtxOPVb1F4nQvYfV1pHCJYlVZxHqQ015xKFHYXY28XEKh4EcfIEQ7H++2oGACxEaf8bxiiIVm3U8TAazAq9SuvXR4DCy1hnYlpvIQX6J2GX7cefgrgdm0VTGUtzxSHA119CWbTJHxVjJPL9W+o2GpfFYTMD6BEZo8FrRfEvTmrpEoumjQPLd5v35ScOL2ROnjUeW/uwL4WcmfRvo0VZveDWlMGXebWzCknpPIp2n3rj3BWFHf4JPs+WQZxFUv11aihrAyGicRS48H8nJ8sFzLNnerom9X995vRnsHQXabjwDby58YLMoLxB1ypnH1lvm6EH3ctIiVWXHYr1CgziY+pDe0A+rjsCF6SjTp9sMi6tAwnrkPbfjAhT4A55cBjpVoSVl9tp9jd3g1PErbOWpaaHFsKH0VHjfhhMhqBNVkeOQ8F8gAwSbyIYFgQzS8xPJicYP/MlAvyHcCbrR7pxmVFmba5oVF8cY4thahEB6QmjOdioD+2y6JbE30G/+Slpzu0FE9B0Vc7HSRHFDQeckzAGzZuU+Gzie3xxEdzTaqrqdU2wQu+GnQ4KMVp9UY4BjNvDcS5M2AqfTdUxvG6IC4ChUUSfkLKuyG1AWQytxjfVTFx4GHc/Pvtta55JtZ+NE1pY=
matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - rvm: 2.6
      env: RSPEC_RUBYOPT="--jit"
    - rvm: ruby-head
      env: RSPEC_RUBYOPT="--jit"
env:
  global:
    - CC_TEST_REPORTER_ID=8f450c1a3ba1c7589d8bf7d937f53e540f23e2c875650a61fc36f1e6682a5ab4
